<a href="https://colab.research.google.com/github/walkerstipe/Surreal_GAN/blob/main/Recurrent_NETWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Processing /root/.cache/pip/wheels/46/25/27/7707005c1cb27e1ffc8277b004ac295e34767b02b44d73d6be/keras_utils-1.0.13-cp37-none-any.whl
(100, 3) (1000, 3)
models already exist
32/32 - 1s - loss: 1.1244 - accuracy: 0.9080


In [ ]:
# example of saving sub-models for later use in a stacking ensemble
from sklearn.datasets import make_blobs
import tensorflow
!pip install keras.utils
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from matplotlib import pyplot
from os import makedirs
from numpy.random import randn
import numpy as np
from sklearn.metrics import accuracy_score

# fit model on dataset
def fit_model(trainX, trainy):
	# define model
	model = Sequential()
	model.add(Dense(25, input_dim=3, activation='relu'))
	model.add(Dense(3, activation='softmax'))
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	# fit model
	model.fit(trainX, trainy, epochs=500, batch_size=1, verbose=0)
	return model

# generate 2d classification dataset
X, y = make_blobs(n_samples=1100, centers=3, n_features=3, cluster_std=2, random_state=2)
#X, y = make_blobs(n_samples=1100, centers=3, n_features=3, cluster_std=2, random_state=2)

# one hot encode output variable
y = to_categorical(y)
# split into train and test
n_train = 100
trainX, testX = X[:n_train, :], X[n_train:, :]
trainy, testy = y[:n_train], y[n_train:]

trainX = trainX[:5]
trainy = trainy[:5]
# print('trainX: ', trainX)
# print('trainy: ', trainy)
print(trainX.shape, testX.shape)

# fit model
model = Sequential()
model.add(Dense(25, input_dim=3, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit model
model.fit(trainX, trainy, epochs=500, batch_size=1, verbose=0)
_, acc = model.evaluate(testX, testy, verbose=2)
trainX, testX = X[:n_train, :], X[n_train:, :]
trainy, testy = y[:n_train], y[n_train:]
trainX = trainX[5:]
trainy = trainy[5:]
model.fit(trainX, trainy, epochs=500, batch_size=1, verbose=0)

#model = fit_model(trainX, trainy)

_, acc = model.evaluate(testX, testy, verbose=2)

Processing /root/.cache/pip/wheels/46/25/27/7707005c1cb27e1ffc8277b004ac295e34767b02b44d73d6be/keras_utils-1.0.13-cp37-none-any.whl
(5, 3) (1000, 3)
32/32 - 0s - loss: 2.9477 - accuracy: 0.4700
32/32 - 0s - loss: 1.0868 - accuracy: 0.9070


In [ ]:
trainX, testX = X[:n_train, :], X[n_train:, :]
trainy, testy = y[:n_train], y[n_train:]

# trainX = trainX[50:]
# trainy = trainy[:50]
trainy = trainy[50:]
trainy
# np.shape(trainX)

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0

In [ ]:
#need to figure out dataset and data set structure, (stratified alternating i think)
#later.

In [ ]:
print(np.shape(testX), np.shape(testy_enc), np.shape(testy))
testy_enc = to_categorical(testy)
testy_enc[0]
#testy[0]

(1000, 3) (1000, 3, 2) (1000, 3)


array([[1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [ ]:
model.evaluate(testX, testy, verbose=2)
# testy

32/32 - 0s - loss: 2.9419 - accuracy: 0.3280


[2.941871166229248, 0.328000009059906]

In [ ]:
trainX, testX = X[0, :], X[0, :]
trainX
testX

array([-3.06292221, -4.98466574])

In [ ]:
trainX, testX = X[:n_train, :], X[n_train:, :]
trainX
testX

array([[-2.36039398, -9.99049779],
       [-4.89139479, -0.62688136],
       [-1.69973447, -1.1847517 ],
       ...,
       [ 1.63592115, -3.18644588],
       [ 1.30143397, -8.75325813],
       [-0.16497425, -6.13314742]])

In [ ]:
print(np.shape(X))
print(np.shape(y))

(1100, 2)
(1100, 3)


In [ ]:
print(X[0][0])
print(y[0][0])

-3.0629222147804995
0.0


In [ ]:
model = fit_model(trainX, trainy)
