In [1]:
!git clone https://github.com/openai/gym.git

Cloning into 'gym'...


In [19]:
#what about this as the code groundwork/simplest possible experiment/example
#to show how we gonna do this empathy shit??? (cuz i need papers eh?)

#convert to functions aka pretty-fi(AFTER VERSION CONTROLLING)
#make sure shit works, (prob need to make the other environment too. easier in pycharm?)

print('Anakin: "Its working!"')

my_map = [
        "SFFFFFFF",
        "FFFFFFFF",
        "FFFHFFFF",
        "FFFFFHFF",
        "FFFHFFFF",
        "FHHFFFHF",
        "FHFFHFHF",
        "GFFHFFFF"
    ]

import gym
import numpy as np
#import WeightedSum 
#from gym.envs.registration import register
#env = gym.make('FrozenLake-v0', desc='8x8')
#env = gym.make('FrozenLake-v0', desc=my_map)
env = gym.make('FrozenLake8x8-v0')
#env = gym.make('FrozenLake-v0', desc=custom_map)
#env = gym.make('FrozenLake8x8-v0')
#env = gym.make('8x8_v2')

print("observation space: ", env.observation_space.n)
print("action space: ", env.action_space.n)

#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 20000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

#print( "Score over time: " +  str(sum(rList)/num_episodes))


#Get score
#for playThroughs in range(10):
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        #Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
    
print( "Score over time Q: " +  str(sum(rList)/num_episodes))
    #print( Q)

################################################
#Q2 is second agent to be combined with the first
Q2 = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q2[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q2-Table with new knowledge
        Q2[s,a] = Q2[s,a] + lr*(r + y*np.max(Q2[s1,:]) - Q2[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
    
#Get score
#for playThroughs in range(10):
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q2[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        #Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
print( "Score over time Q2: " +  str(sum(rList)/num_episodes))
##############################################################

################################################
#Now we just try and run it
Q3 = (Q * Q2) / 2
#for playThroughs in range(10):
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q3[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        #Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
print( "Score over time Q3: " +  str(sum(rList)/num_episodes))

# =============================================================================
# print("Q[0][0]", Q[0][0] )
# print((Q[0][0] + Q2[0][0])/2)
# print((Q[0][0]))
# =============================================================================

#Now we just try and run it
def WeightedSum(Q, Q2):
  Q_ = np.copy(Q)
  for y in range(len(Q[:,:])):
    for x in range(len(Q[0])):
      #print(x, ' ', y)
      Q_[y][x] = (Q[y][x] + Q2[y][x]) / 2
  return Q_
Q4 =  WeightedSum(Q, Q2)
#Q4 = WeightedSum.wsum(Q, Q2)
#print(Q4)
#for playThroughs in range(10):
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q4[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        #Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
print( "Score over time Q4: " +  str(sum(rList)/num_episodes))
# =============================================================================
# print(Q)
# print(Q2)
# print(Q3)
# print(Q4)
# =============================================================================
# ===================================


Anakin: "Its working!"
observation space:  64
action space:  4
Score over time Q: 0.32535
Score over time Q2: 0.169
Score over time Q3: 0.0175
Score over time Q4: 0.3645


In [17]:
#so... everythings working... but scores are wildly different depending on 
#environment...?

#increase number of episodes?
#score is just a feature of the environment, (optimality can just be low right?...)
#this implementation is shitty, (Seems fine, but let's make a NN anyhow)

In [6]:
custom_map = [
    'SFFHF',
    'HFHFF',
    'HFFFH',
    'HHHFH',
    'HFFFG'
]
 
env = gym.make('FrozenLake-v0', desc=custom_map)
env.reset()
env.render()


SFFHF
HFHFF
HFFFH
HHHFH
HFFFG


In [ ]:
#1300000/21000
#for every 1 ai nerd in the U.S. ... there are 62 lawyers...

61.904761904761905

In [ ]:
np.shape(Q2)
print(np.average(Q,Q2))
#Q2

TypeError: ignored

In [ ]:
def WeightedSum(Q, Q2):
  Q_ = np.copy(Q)
  for y in range(len(Q[:,:])):
    for x in range(len(Q[0])):
      #print(x, ' ', y)
      Q_[y][x] = (Q[y][x] + Q2[y][x]) / 2
  return Q_

In [ ]:
print(WeightedSum(Q, Q2))

[[3.15736105e-03 4.86327405e-03 1.09712950e-02 4.31863486e-03]
 [1.61097671e-03 1.26546630e-02 4.50838772e-03 4.38152866e-03]
 [1.99446843e-03 5.30380375e-03 1.18162058e-02 2.04051806e-03]
 [1.93062346e-03 8.25649649e-03 3.97368788e-02 2.11669317e-03]
 [1.23214516e-03 1.65774257e-03 3.71109168e-02 2.59399717e-03]
 [1.36296676e-03 3.76915773e-02 2.77524536e-02 4.20873072e-03]
 [2.48791165e-03 4.73483853e-02 1.18903142e-01 3.56701667e-04]
 [2.00953406e-03 5.56591154e-02 2.32590150e-03 1.54895834e-03]
 [1.51318666e-03 2.51134938e-03 3.20992700e-03 1.04747198e-02]
 [1.61666464e-03 3.26641269e-03 3.87170178e-03 1.37676589e-02]
 [1.43664380e-03 2.04069496e-03 2.13749430e-03 2.06068612e-02]
 [2.58040224e-04 4.98504135e-04 1.99240513e-04 5.91646740e-02]
 [1.51713719e-03 1.36876704e-03 1.19855189e-03 4.32706531e-02]
 [2.74169402e-02 1.81542532e-03 1.31362345e-03 3.29489496e-02]
 [1.94836234e-03 2.51587751e-03 1.22792353e-01 1.22223875e-03]
 [2.02590532e-03 1.03820304e-03 5.04663901e-02 1.077460

In [ ]:
Q[0][1]

0.006507379454077243